<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CsvLibrarian</RootNamespace>
    <AssemblyName>CsvLibrarian</AssemblyName>
    <StartupObject>CsvLibrarian.Program</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <OptionInfer>On</OptionInfer>
    <OptionCompare>Binary</OptionCompare>
    <Nullable>disable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
    <Import Include="System.Linq" />
    <Import Include="Microsoft.VisualBasic" />
  </ItemGroup>

</Project>
